# -*- coding: utf-8 -*-
"""AP Research Thyroid Cancer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyReqzFVVCUEm1LSa_sTdvK_JOuaq2xz
"""

# Download the dataset
from google.colab import files

uploaded= files.upload()

# Import libraries
import numpy as np
import pandas as pd
import seaborn as sns

#Create dataframe
Thyroid_Recurrence = pd.read_csv("Thyroid_Diff.csv")

#See size of dataset
Thyroid_Recurrence.shape

# First five rows of dataframe
Thyroid_Recurrence.head()

#Histplot for patient recurrence
sns.histplot(Thyroid_Recurrence['Recurred'])

# Preprocessing recurred variable
Thyroid_Recurrence['Recurred'].replace('No',0,inplace=True)
Thyroid_Recurrence['Recurred'].replace('Yes',1,inplace=True)

#Histogram of the stages of thyroid cancer
sns.histplot(Thyroid_Recurrence['Stage'])

# Stage variable preprocessing
Thyroid_Recurrence['Stage'].replace('I',0,inplace=True)
Thyroid_Recurrence['Stage'].replace('II',1,inplace=True)
Thyroid_Recurrence['Stage'].replace('IVB',2,inplace=True)
Thyroid_Recurrence['Stage'].replace('III',3,inplace=True)
Thyroid_Recurrence['Stage'].replace('IVA',4,inplace=True)

# Determining if there are missing values within the data

np.sum(pd.isnull(Thyroid_Recurrence))

#Boxplot of patient ages
sns.boxplot(Thyroid_Recurrence['Age'])

#Histogram of ages
sns.histplot(Thyroid_Recurrence['Age'])

#Boxplot of patient smoking status
sns.boxplot(Thyroid_Recurrence['Smoking'])

# Smoking preprocessing
Thyroid_Recurrence['Smoking']=Thyroid_Recurrence['Smoking'].replace("No",0)
Thyroid_Recurrence['Smoking']=Thyroid_Recurrence['Smoking'].replace("Yes",1)

# Boxplot of gender
sns.boxplot(Thyroid_Recurrence['Gender'])

# Preprocessing gender
Thyroid_Recurrence['Gender']=Thyroid_Recurrence['Gender'].replace("F",0)
Thyroid_Recurrence['Gender']=Thyroid_Recurrence['Gender'].replace("M",1)

#Histogram of smoking status
sns.histplot(Thyroid_Recurrence['Hx Smoking'])

# Smoking preprocessing
Thyroid_Recurrence['Hx Smoking']= Thyroid_Recurrence['Hx Smoking'].replace("No",0)
Thyroid_Recurrence['Hx Smoking']= Thyroid_Recurrence['Hx Smoking'].replace("Yes",1)

print(Thyroid_Recurrence['Pathology'])

#Histogram of patient responses to treatment
sns.histplot(Thyroid_Recurrence['Response'])

# Preprocessing response variable
Thyroid_Recurrence['Response']=Thyroid_Recurrence['Response'].replace("Indeterminate",0)
Thyroid_Recurrence['Response']=Thyroid_Recurrence['Response'].replace("Excellent",1)
Thyroid_Recurrence['Response']=Thyroid_Recurrence['Response'].replace("Structural Incomplete",2)
Thyroid_Recurrence['Response']=Thyroid_Recurrence['Response'].replace("Biochemical Incomplete",3)

#Histogram of radiotherapy status
sns.histplot(Thyroid_Recurrence['Hx Radiothreapy'])

# Preprocessing radiotherapy variable
Thyroid_Recurrence['Hx Radiothreapy']=Thyroid_Recurrence['Hx Radiothreapy'].replace("No",0)
Thyroid_Recurrence['Hx Radiothreapy']=Thyroid_Recurrence['Hx Radiothreapy'].replace("Yes",1)

# Boxplot of thyroid function
sns.boxplot(Thyroid_Recurrence['Thyroid Function'])

# Preprocessing function variable
Thyroid_Recurrence['Thyroid Function']=Thyroid_Recurrence['Thyroid Function'].replace("Euthyroid",0)
Thyroid_Recurrence['Thyroid Function']=Thyroid_Recurrence['Thyroid Function'].replace("Clinical Hyperthyroidism",1)
Thyroid_Recurrence['Thyroid Function']=Thyroid_Recurrence['Thyroid Function'].replace("Clinical Hypothyroidism",2)
Thyroid_Recurrence['Thyroid Function']=Thyroid_Recurrence['Thyroid Function'].replace("Subclinical Hyperthyroidism",3)
Thyroid_Recurrence['Thyroid Function']=Thyroid_Recurrence['Thyroid Function'].replace("Subclinical Hypothyroidism",4)

sns.boxplot(Thyroid_Recurrence['Physical Examination'])

Thyroid_Recurrence['Physical Examination']=Thyroid_Recurrence['Physical Examination'].replace("Single nodular goiter-left",0)
Thyroid_Recurrence['Physical Examination']=Thyroid_Recurrence['Physical Examination'].replace("Multinodular goiter",1)
Thyroid_Recurrence['Physical Examination']=Thyroid_Recurrence['Physical Examination'].replace("Single nodular goiter-right",2)
Thyroid_Recurrence['Physical Examination']=Thyroid_Recurrence['Physical Examination'].replace("Normal",3)
Thyroid_Recurrence['Physical Examination']=Thyroid_Recurrence['Physical Examination'].replace("Diffuse goiter",4)

sns.histplot(Thyroid_Recurrence['Adenopathy'])

Thyroid_Recurrence['Adenopathy']=Thyroid_Recurrence['Adenopathy'].replace("No",0)
Thyroid_Recurrence['Adenopathy']=Thyroid_Recurrence['Adenopathy'].replace("Right",1)
Thyroid_Recurrence['Adenopathy']=Thyroid_Recurrence['Adenopathy'].replace("Extensive",2)
Thyroid_Recurrence['Adenopathy']=Thyroid_Recurrence['Adenopathy'].replace("Left",3)
Thyroid_Recurrence['Adenopathy']=Thyroid_Recurrence['Adenopathy'].replace("Bilateral",4)
Thyroid_Recurrence['Adenopathy']=Thyroid_Recurrence['Adenopathy'].replace("Posterior",5)

sns.histplot(Thyroid_Recurrence['Pathology'])

Thyroid_Recurrence['Pathology']=Thyroid_Recurrence['Pathology'].replace("Micropapillary",0)
Thyroid_Recurrence['Pathology']=Thyroid_Recurrence['Pathology'].replace("Papillary",1)
Thyroid_Recurrence['Pathology']=Thyroid_Recurrence['Pathology'].replace("Follicular",2)
Thyroid_Recurrence['Pathology']=Thyroid_Recurrence['Pathology'].replace("Hurthel cell",3)

sns.histplot(Thyroid_Recurrence['Focality'])

Thyroid_Recurrence['Focality']=Thyroid_Recurrence['Focality'].replace("Uni-Focal",0)
Thyroid_Recurrence['Focality']=Thyroid_Recurrence['Focality'].replace("Multi-Focal",1)

sns.histplot(Thyroid_Recurrence['Risk'])

Thyroid_Recurrence['Risk']=Thyroid_Recurrence['Risk'].replace("Low",0)
Thyroid_Recurrence['Risk']=Thyroid_Recurrence['Risk'].replace("Intermediate",1)
Thyroid_Recurrence['Risk']=Thyroid_Recurrence['Risk'].replace("High",2)

sns.histplot(Thyroid_Recurrence['T'])

Thyroid_Recurrence['T']=Thyroid_Recurrence['T'].replace("T1a",0)
Thyroid_Recurrence['T']=Thyroid_Recurrence['T'].replace("T1b",1)
Thyroid_Recurrence['T']=Thyroid_Recurrence['T'].replace("T2",2)
Thyroid_Recurrence['T']=Thyroid_Recurrence['T'].replace("T3a",3)
Thyroid_Recurrence['T']=Thyroid_Recurrence['T'].replace("T3b",4)
Thyroid_Recurrence['T']=Thyroid_Recurrence['T'].replace("T4a",5)
Thyroid_Recurrence['T']=Thyroid_Recurrence['T'].replace("T4b",6)

sns.histplot(Thyroid_Recurrence['N'])

Thyroid_Recurrence['N']=Thyroid_Recurrence['N'].replace("N0",0)
Thyroid_Recurrence['N']=Thyroid_Recurrence['N'].replace("N1b",1)
Thyroid_Recurrence['N']=Thyroid_Recurrence['N'].replace("N1a",2)

sns.histplot(Thyroid_Recurrence['M'])

Thyroid_Recurrence['M']=Thyroid_Recurrence['M'].replace("M0",0)
Thyroid_Recurrence['M']=Thyroid_Recurrence['M'].replace("M1",1)

# Creating X and Y data
y=Thyroid_Recurrence['Recurred']
x=Thyroid_Recurrence.drop(columns=['Recurred'])

#Splitting the data into training and testing
from sklearn.model_selection import train_test_split

X_train, X_test,y_train, y_test = train_test_split(x,y,test_size=.30,random_state=9)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(y_train)

print(y_train.value_counts())

print(y_test.value_counts())

# Logistic regression model coding
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(random_state=9)
logistic_model.fit(X_train , y_train)

# Logistic Regression model accuracy calculation
from sklearn.metrics import accuracy_score
predictions = logistic_model.predict(X_test)
score = accuracy_score(y_test, predictions)
print('Logistic Regression Model Accuracy: {:.2%}'.format(score))

# Determining which features were most important for Logistic Regression Model
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)


coefficients = logistic_model.coef_[0]

feature_importance = pd.DataFrame({'Feature': x.columns, 'Importance': np.abs(coefficients)})
feature_importance = feature_importance.sort_values('Importance', ascending=True)
feature_importance.plot(x='Feature', y='Importance', kind='barh', figsize=(10, 6))

# Training and calcuating accuracy for Ridge Classifier model
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import accuracy_score
clf = RidgeClassifier(random_state=9).fit(X_train, y_train)
predictions2=clf.predict(X_test)
score2= accuracy_score(y_test, predictions2)
print('Ridge Classifer Accuracy: {:.2%}'.format(score2))

# Determining which variables are most important for Ridge model
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)


coefficients = clf.coef_[0]

feature_importance = pd.DataFrame({'Feature': x.columns, 'Importance': np.abs(coefficients)})
feature_importance = feature_importance.sort_values('Importance', ascending=True)
feature_importance.plot(x='Feature', y='Importance', kind='barh', figsize=(10, 6))

# Training and calcuating accuracy for Random FOrest model
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
RandomForest= RandomForestClassifier(random_state=100).fit(X_train, y_train)
RF_predictions=RandomForest.predict(X_test)
RF_score=accuracy_score(y_test, RF_predictions)
print('RandomForest Classifer Accuracy: {:.2%}'.format(RF_score))

# Training and calcuating accuracy for KNN model
from sklearn.neighbors import KNeighborsClassifier
neigh=KNeighborsClassifier(n_neighbors=15)
neigh.fit(X_train, y_train)
KNN_predictions=neigh.predict(X_test)
KNN_score=accuracy_score(y_test, KNN_predictions)
print('KNN Classifer Accuracy: {:.2%}'.format(KNN_score))

# Training and calcuating accuracy for SVM model
from sklearn import svm
clf = svm.SVC(kernel='linear',C=.1,gamma='auto')
clf.fit(X_train, y_train)
svc_predictions=clf.predict(X_test)
svc_score=accuracy_score(y_test, svc_predictions)
print('SVC Classifer Accuracy: {:.2%}'.format(svc_score))

# Determining optimal hyperparamters for SVM model
from sklearn.model_selection import GridSearchCV
gs= GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[.01,.05,.1,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,],
    'kernel':['rbf','linear']},
     cv=20,
     return_train_score=False,
     )
gs.fit(x,y)
pd.DataFrame(gs.cv_results_)[['param_C','param_kernel','mean_test_score']]

# Training and calcuating accuracy for ExtraTrees model
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score
ExtraTrees= ExtraTreesClassifier(random_state=10).fit(X_train, y_train)
ET_predictions=ExtraTrees.predict(X_test)
ET_score=accuracy_score(y_test, ET_predictions)
print('ExtraTrees Classifer Accuracy: {:.2%}'.format(ET_score))

# Training and calcuating accuracy for Xgboost model
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
xgb= XGBClassifier(random_state=6).fit(X_train, y_train)
xgb_predictions=xgb.predict(X_test)
xgb_score=accuracy_score(y_test, xgb_predictions)
print('XGB Classifer Accuracy: {:.2%}'.format(xgb_score))

# Training and calcuating accuracy for Decision tree model
from sklearn import tree
dt= tree.DecisionTreeClassifier(random_state=100).fit(X_train, y_train)
dt_predictions=dt.predict(X_test)
dt_score=accuracy_score(y_test, dt_predictions)
print('Decision Tree Accuracy: {:.2%}'.format(dt_score))

# Training and calcuating accuracy LightGBM model
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score
lgbm= LGBMClassifier(random_state=5).fit(X_train, y_train)
lgbm_predictions=lgbm.predict(X_test)
lgbm_score=accuracy_score(y_test, lgbm_predictions)
print('LGBM Classifer Accuracy: {:.2%}'.format(lgbm_score))

#Determining version of python
!python --version

# Determnining numpy version
print(np.__version__)

# Installing catboost model
!pip install catboost==1.2.8

# Training and calcuating accuracy for Catboost model
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score
cat= CatBoostClassifier(random_state=100).fit(X_train, y_train)
cat_predictions=cat.predict(X_test)
cat_score=accuracy_score(y_test, cat_predictions)
print('CatBoost Classifer Accuracy: {:.2%}'.format(cat_score))

# Training and calcuating accuracy for ANN model
import tensorflow as tf
from tensorflow import keras

y_train=np.clip(y_train,0,1)
y_test=np.clip(y_test,0,1)
ANN= tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape= (16,1)),
  keras.layers.BatchNormalization(),
  tf.keras.layers.Dense(300, activation='relu'),
  keras.layers.BatchNormalization(),
  tf.keras.layers.Dense(300, activation='relu'),
  keras.layers.BatchNormalization(),
  tf.keras.layers.Dense(300, activation='relu'),
  keras.layers.BatchNormalization(),
  tf.keras.layers.Dense(300, activation='relu'),
  keras.layers.BatchNormalization(),
  tf.keras.layers.Dense(300, activation='relu'),
  keras.layers.BatchNormalization(),
  tf.keras.layers.Dense(2, activation = 'softmax')])
loss= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
ANN.compile(optimizer='adam', loss=loss, metrics=['accuracy'])
ANN.fit(X_train, y_train, epochs=130)
ANN_predictions=ANN.predict(X_test).argmax(axis=1)
ANN_score=accuracy_score(y_test, ANN_predictions)
print('ANN Classifer Accuracy: {:.2%}'.format(ANN_score))